### ISSUE TITLE
Exception in server tick loop, happens when creating a world

### ISSUE THREAD

**Issue by JustKade** [ghzdude/MCRandomizer#1]
Not sure exactly what is going on in this.

Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "name" is null
	at net.minecraft.world.level.storage.loot.LootTable.lambda$getPool$1(LootTable.java:202) ~[client-1.19.2-20220805.130853-srg.jar%23383!/:?] {re:mixin,re:classloading,pl:mixin:APP:balm.mixins.json:LootTableMixin,pl:mixin:APP:botania_xplat.mixins.json:LootTableMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorLootTable,pl:mixin:A}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?] {}
	at net.minecraft.world.level.storage.loot.LootTable.getPool(LootTable.java:202) ~[client-1.19.2-20220805.130853-srg.jar%23383!/:?] {re:mixin,re:classloading,pl:mixin:APP:balm.mixins.json:LootTableMixin,pl:mixin:APP:botania_xplat.mixins.json:LootTableMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorLootTable,pl:mixin:A}
	at com.ghzdude.randomizer.LootRandomizer.randomizeLoot(LootRandomizer.java:57) ~[MCrandomizer-0.2.jar%23323!/:0.2] {re:classloading}
	at com.ghzdude.randomizer.LootRandomizer.randomizeLootTables(LootRandomizer.java:45) ~[MCrandomizer-0.2.jar%23323!/:0.2] {re:classloading}
	at com.ghzdude.randomizer.LootRandomizer.start(LootRandomizer.java:174) ~[MCrandomizer-0.2.jar%23323!/:0.2] {re:classloading}
	at com.ghzdude.randomizer.__LootRandomizer_start_ServerStartedEvent.invoke(.dynamic) ~[MCrandomizer-0.2.jar%23323!/:0.2] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:109) ~[forge-1.19.2-43.2.21-universal.jar%23388!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:629) ~[client-1.19.2-20220805.130853-srg.jar%23383!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23383!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}

This is the crash report that I got.

**Comment by ghzdude** [comment]
is this the entire crash report? they usually information on what mods are installed as well iirc

you should be able to drag the report into github as an attachment

**Comment by ghzdude** [comment]
version 0.3 should fix this, reopen the issue if the crash persists
