### ISSUE TITLE
When running server on Forge 1.21.1, crashes immediately

### ISSUE THREAD

**Issue by FrickerMan23** [ghzdude/MCRandomizer#11]
for some reason whenever i start hosting a forge 1.21.1 server, the server crashes :(

CRASH LOG:
```
[08:57:49] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        MC Randomizer (randomizer) encountered an error during the common_setup event phase
§7java.lang.NoClassDefFoundError: com/mojang/blaze3d/platform/WindowEventHandler
]
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.21.1-52.0.16/net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:269) ~[fmlcore-1.21.1-52.0.16.jar:1.0] {}
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.21.1-52.0.16/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:233) ~[fmlcore-1.21.1-52.0.16.jar:1.0] {}
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.21.1-52.0.16/net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:206) ~[fmlcore-1.21.1-52.0.16.jar:1.0] {}
        at TRANSFORMER/forge@52.0.16/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:31) ~[forge-1.21.1-52.0.16-universal.jar:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Main.main(Main.java:129) ~[forge-1.21.1-52.0.16-server.jar:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.1-52.0.16/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:85) ~[fmlloader-1.21.1-52.0.16.jar!/:?] {}
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.1-52.0.16/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:69) ~[fmlloader-1.21.1-52.0.16.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:116) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.1.jar!/:?] {}
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.1.jar!/:?] {}
        at net.minecraftforge.bootstrap@2.1.3/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.3.jar!/:?] {}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.3.jar:2.1.3] {}
        at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.3.jar:2.1.3] {}
        at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.3.jar:2.1.3] {}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at net.minecraftforge.bootstrap.shim.Main.main(Main.java:97) [forge-1.21.1-52.0.16-shim.jar:2.1.3] {}
```

**Comment by ghzdude** [comment]
this might be fixed with hotfix F, let me know if it's still an issue
